# Numpy.Split
UNet Reference 에서 dataset을 npy file로 요구함

하나의 npy 파일에 모든 dataset의 array (image, mask 따로)정보가 담겨야 함

빈 리스트를 생성한 뒤, array를 append 하고 list를 array로 바꾸는 방식으로 만들어봤으나 Reference dataset의 형태와 다름

이미지 array 하나하나가 개별 array로 들어가 있음

그에 맞춰 전처리하기위한 실험을 진행

In [ ]:
import os
import PIL
import numpy as np
from PIL import Image
from tqdm.notebook import tqdm

In [ ]:
!gdown 1z70VmSxCOPNvCc-wna8W08wzvguESYqL
!gdown 10eezc97N7TopvZEl46R-Mv04XFGx3-LV
!unzip /content/NPYdata_0729.zip
!unzip /content/jpg_png_512resize_binary_labelsplit_220728.zip

Downloading...
From: https://drive.google.com/uc?id=1z70VmSxCOPNvCc-wna8W08wzvguESYqL
To: /content/NPYdata_0729.zip
100% 141M/141M [00:01<00:00, 131MB/s]
Downloading...
From: https://drive.google.com/uc?id=10eezc97N7TopvZEl46R-Mv04XFGx3-LV
To: /content/jpg_png_512resize_binary_labelsplit_220728.zip
100% 27.4M/27.4M [00:00<00:00, 49.9MB/s]


In [ ]:
!gdown 1Tu0duIUcxoCpb7LUTTfEkCrbgBjOs8Y8
!unzip /content/NPYdata.zip

In [ ]:
!gdown 1nOmp0viaKB1Ne7hwMyKH8XRXxESh06uw
!unzip /content/images.npy.zip

Downloading...
From: https://drive.google.com/uc?id=1nOmp0viaKB1Ne7hwMyKH8XRXxESh06uw
To: /content/images.npy.zip
100% 878M/878M [00:05<00:00, 170MB/s]
Archive:  /content/images.npy.zip
  inflating: images.npy              


In [ ]:
asd = np.load('/content/data/label1/label1_image.npy')
asd = np.split(asd,304) # np.split(array, indices or section, axis=0) , 배열분할
asd = asd[0]
asd.squeeze() # 차원축소

array([[249, 249, 249, ..., 106, 106, 106],
       [242, 242, 242, ..., 106, 106, 106],
       [246, 246, 246, ..., 107, 106, 106],
       ...,
       [197, 195, 192, ..., 197, 197, 197],
       [201, 198, 195, ..., 197, 197, 197],
       [208, 204, 200, ..., 197, 197, 197]], dtype=int16)

In [ ]:
aa = np.load('/content/images.npy',allow_pickle=True)

In [ ]:
path_list = os.listdir('/content/make_data/1/images/')
path_list2 = os.listdir('/content/make_data/2/images/')
path_list3 = os.listdir('/content/make_data/3/images/')
path_list4 = os.listdir('/content/make_data/4/images/')
len(path_list),len(path_list2),len(path_list3),len(path_list4)

(304, 287, 188, 115)

In [ ]:
a = np.load('/content/npyData/images/a_01.npy',allow_pickle=False)
b = np.load('/content/npyData/images/a_010.npy',allow_pickle=False)

In [ ]:
a

array([[[186, 178, 185],
        [182, 175, 182],
        [195, 188, 195],
        ...,
        [178, 176, 177],
        [177, 175, 176],
        [174, 172, 173]],

       [[186, 180, 184],
        [181, 175, 179],
        [192, 186, 190],
        ...,
        [178, 176, 177],
        [175, 173, 174],
        [172, 170, 171]],

       [[186, 180, 183],
        [180, 174, 177],
        [187, 182, 185],
        ...,
        [177, 176, 177],
        [175, 173, 174],
        [172, 170, 171]],

       ...,

       [[133, 121, 107],
        [134, 122, 110],
        [136, 123, 114],
        ...,
        [152, 143, 143],
        [165, 155, 155],
        [166, 156, 157]],

       [[136, 124, 110],
        [138, 126, 113],
        [139, 126, 118],
        ...,
        [157, 148, 149],
        [166, 156, 157],
        [166, 156, 157]],

       [[138, 124, 111],
        [139, 125, 114],
        [139, 124, 116],
        ...,
        [162, 153, 154],
        [167, 157, 158],
        [166, 155, 157]]

In [ ]:
img

array([[[ 52,  50,  61],
        [ 52,  50,  61],
        [ 54,  54,  63],
        ...,
        [149, 144, 138],
        [150, 146, 139],
        [149, 145, 136]],

       [[ 49,  47,  58],
        [ 50,  50,  60],
        [ 53,  53,  62],
        ...,
        [150, 145, 139],
        [150, 145, 139],
        [151, 145, 139]],

       [[ 45,  45,  55],
        [ 48,  48,  59],
        [ 52,  52,  60],
        ...,
        [149, 144, 138],
        [152, 146, 141],
        [153, 146, 140]],

       ...,

       [[121, 116, 110],
        [124, 117, 113],
        [123, 115, 112],
        ...,
        [132, 127, 123],
        [134, 126, 123],
        [135, 127, 124]],

       [[118, 113, 108],
        [118, 112, 108],
        [119, 111, 108],
        ...,
        [130, 125, 121],
        [132, 127, 123],
        [134, 128, 124]],

       [[119, 114, 110],
        [116, 111, 107],
        [119, 113, 110],
        ...,
        [129, 124, 120],
        [132, 127, 123],
        [133, 128, 124]]

In [ ]:
import numpy as np
test = np.load('/content/npyData/images/a_01.npy')
test

In [ ]:
len(test)

512

In [ ]:
label1 = np.load('/content/data/label1/label1_image.npy')
label1

array([[[249, 249, 249, ..., 106, 106, 106],
        [242, 242, 242, ..., 106, 106, 106],
        [246, 246, 246, ..., 107, 106, 106],
        ...,
        [197, 195, 192, ..., 197, 197, 197],
        [201, 198, 195, ..., 197, 197, 197],
        [208, 204, 200, ..., 197, 197, 197]],

       [[ 15,  15,  14, ..., 151, 142, 131],
        [ 15,  15,  14, ..., 151, 141, 131],
        [ 14,  14,  14, ..., 151, 140, 131],
        ...,
        [ 83,  88,  91, ..., 108, 107, 111],
        [ 84,  86,  90, ..., 108, 105, 107],
        [ 85,  84,  86, ..., 110, 105, 106]],

       [[106, 106, 106, ..., 127, 127, 127],
        [106, 106, 106, ..., 127, 127, 127],
        [106, 106, 106, ..., 128, 128, 128],
        ...,
        [ 27,  27,  26, ...,  42,  42,  42],
        [ 27,  26,  26, ...,  44,  42,  41],
        [ 26,  26,  26, ...,  55,  53,  52]],

       ...,

       [[197, 197, 199, ..., 101, 101, 101],
        [198, 199, 200, ..., 102, 101, 101],
        [201, 201, 201, ..., 102, 102, 101

In [ ]:
## split
label_1_test = np.split(label1,304)
label_1_test = np.array(label_1_test)
label_1_test.squeeze()
# label_1_test.shape
# label_1_test = np.squeeze(label_1_test)
# label_1_test.shape

array([[[249, 249, 249, ..., 106, 106, 106],
        [242, 242, 242, ..., 106, 106, 106],
        [246, 246, 246, ..., 107, 106, 106],
        ...,
        [197, 195, 192, ..., 197, 197, 197],
        [201, 198, 195, ..., 197, 197, 197],
        [208, 204, 200, ..., 197, 197, 197]],

       [[ 15,  15,  14, ..., 151, 142, 131],
        [ 15,  15,  14, ..., 151, 141, 131],
        [ 14,  14,  14, ..., 151, 140, 131],
        ...,
        [ 83,  88,  91, ..., 108, 107, 111],
        [ 84,  86,  90, ..., 108, 105, 107],
        [ 85,  84,  86, ..., 110, 105, 106]],

       [[106, 106, 106, ..., 127, 127, 127],
        [106, 106, 106, ..., 127, 127, 127],
        [106, 106, 106, ..., 128, 128, 128],
        ...,
        [ 27,  27,  26, ...,  42,  42,  42],
        [ 27,  26,  26, ...,  44,  42,  41],
        [ 26,  26,  26, ...,  55,  53,  52]],

       ...,

       [[197, 197, 199, ..., 101, 101, 101],
        [198, 199, 200, ..., 102, 101, 101],
        [201, 201, 201, ..., 102, 102, 101

In [ ]:
test = np.split(label1)

In [ ]:
## vsplit
label_1 = np.vsplit(label1,304) # vsplit: 한 개의 배열을 수직축 방향(행 방향, row-wise)으로 분할
# label_1 = np.array(label_1)
label_1
for i in label_1:
  i = i.squeeze()
# label_1.shape

In [ ]:
label_1

[array([[[249, 249, 249, ..., 106, 106, 106],
         [242, 242, 242, ..., 106, 106, 106],
         [246, 246, 246, ..., 107, 106, 106],
         ...,
         [197, 195, 192, ..., 197, 197, 197],
         [201, 198, 195, ..., 197, 197, 197],
         [208, 204, 200, ..., 197, 197, 197]]], dtype=int16),
 array([[[ 15,  15,  14, ..., 151, 142, 131],
         [ 15,  15,  14, ..., 151, 141, 131],
         [ 14,  14,  14, ..., 151, 140, 131],
         ...,
         [ 83,  88,  91, ..., 108, 107, 111],
         [ 84,  86,  90, ..., 108, 105, 107],
         [ 85,  84,  86, ..., 110, 105, 106]]], dtype=int16),
 array([[[106, 106, 106, ..., 127, 127, 127],
         [106, 106, 106, ..., 127, 127, 127],
         [106, 106, 106, ..., 128, 128, 128],
         ...,
         [ 27,  27,  26, ...,  42,  42,  42],
         [ 27,  26,  26, ...,  44,  42,  41],
         [ 26,  26,  26, ...,  55,  53,  52]]], dtype=int16),
 array([[[198, 198, 198, ..., 196, 196, 196],
         [198, 198, 198, ..., 197, 1