In [1]:
!pip install spicy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!gdown 1NHrVNN20YphgVjaOM9Qu6OA7N0JUVHfN # 원본이미지, 마스크이미지 둘 다 PNG인 파일

In [ ]:
!unzip /content/All_PNGData.zip

In [ ]:
import os
import PIL
import numpy as np
from PIL import Image
from tqdm.notebook import tqdm

In [ ]:
# img = Image.open(dir)
# img = np.array(img)
# img = Image.fromarray(img).convert("P")
# img.save(경로)

In [11]:
path = '/content/data/Training/Category_ids/'
path_list = os.listdir(path)

for i in tqdm(path_list):
  dir = path + i
  img = Image.open(dir)
  img = np.array(img)
  img = Image.fromarray(img).convert("P") # 현재 마스크 이미지를 palette형태로 변환
  img.save(dir)

  0%|          | 0/2432 [00:00<?, ?it/s]

In [12]:
len(path_list) # 파일개수확인

2432

In [ ]:
!zip PalettePNGdata.zip -r ./data

In [14]:
import shutil # zip파일 드라이브로 이동
filename = 'PalettePNGdata.zip'
src = '/content/'
dir = '/content/drive/MyDrive/Colab Notebooks/'
shutil.move(src+filename, dir+filename)

'/content/drive/MyDrive/Colab Notebooks/PalettePNGdata.zip'

In [6]:
import numpy as np
import scipy.io

In [15]:
# colormap.mat 만드는 함수
def colormap(rgb=True):
    color_list = np.array(
        [
            0.000, 0.447, 0.741,
            0.850, 0.325, 0.098,
            0.929, 0.694, 0.125,
            0.494, 0.184, 0.556,
            0.466, 0.674, 0.188,
            0.301, 0.745, 0.933,
            0.635, 0.078, 0.184,
            0.300, 0.300, 0.300,
            0.600, 0.600, 0.600,
            1.000, 0.000, 0.000,
            1.000, 0.500, 0.000,
            0.749, 0.749, 0.000,
            0.000, 1.000, 0.000,
            0.000, 0.000, 1.000,
            0.667, 0.000, 1.000,
            0.333, 0.333, 0.000,
            0.333, 0.667, 0.000,
            0.333, 1.000, 0.000,
            0.667, 0.333, 0.000,
            0.667, 0.667, 0.000,
            0.667, 1.000, 0.000,
            1.000, 0.333, 0.000,
            1.000, 0.667, 0.000,
            1.000, 1.000, 0.000,
            0.000, 0.333, 0.500,
            0.000, 0.667, 0.500,
            0.000, 1.000, 0.500,
            0.333, 0.000, 0.500,
            0.333, 0.333, 0.500,
            0.333, 0.667, 0.500,
            0.333, 1.000, 0.500,
            0.667, 0.000, 0.500,
            0.667, 0.333, 0.500,
            0.667, 0.667, 0.500,
            0.667, 1.000, 0.500,
            1.000, 0.000, 0.500,
            1.000, 0.333, 0.500,
            1.000, 0.667, 0.500,
            1.000, 1.000, 0.500,
            0.000, 0.333, 1.000,
            0.000, 0.667, 1.000,
            0.000, 1.000, 1.000,
            0.333, 0.000, 1.000,
            0.333, 0.333, 1.000,
            0.333, 0.667, 1.000,
            0.333, 1.000, 1.000,
            0.667, 0.000, 1.000,
            0.667, 0.333, 1.000,
            0.667, 0.667, 1.000,
            0.667, 1.000, 1.000,
            1.000, 0.000, 1.000,
            1.000, 0.333, 1.000,
            1.000, 0.667, 1.000,
            0.167, 0.000, 0.000,
            0.333, 0.000, 0.000,
            0.500, 0.000, 0.000,
            0.667, 0.000, 0.000,
            0.833, 0.000, 0.000,
            1.000, 0.000, 0.000,
            0.000, 0.167, 0.000,
            0.000, 0.333, 0.000,
            0.000, 0.500, 0.000,
            0.000, 0.667, 0.000,
            0.000, 0.833, 0.000,
            0.000, 1.000, 0.000,
            0.000, 0.000, 0.167,
            0.000, 0.000, 0.333,
            0.000, 0.000, 0.500,
            0.000, 0.000, 0.667,
            0.000, 0.000, 0.833,
            0.000, 0.000, 1.000,
            0.000, 0.000, 0.000,
            0.143, 0.143, 0.143,
            0.286, 0.286, 0.286,
            0.429, 0.429, 0.429,
            0.571, 0.571, 0.571,
            0.714, 0.714, 0.714,
            0.857, 0.857, 0.857,
            1.000, 1.000, 1.000
        ]
    ).astype(np.float32)
    color_list = color_list.reshape((-1, 3)) * 255
    if not rgb: 
        color_list = color_list[:, ::-1]
    return color_list

    
cm5 = {'colormap': [[0, 0, 0],
          [128, 0, 128],
          [0, 128, 64],
          [128, 128, 192],
          [128, 64, 0]]
         }

# cm2 = {'colormap':[[0.        , 0.        , 0.        ],
#         [0.5       , 0.        , 0.        ]]
#          }

def dict_bgr2rgb(colordict):
    rgb = dict()
    keys = colordict.keys()
    for k in keys:
        rgb[k] = colordict[k][::-1]

    return rgb


def dict2array(colordict):
    keys = colordict.keys()
    colorarray = np.zeros((len(keys), 3))
    for ids, k in enumerate(keys):
        colorarray[ids] = np.asarray(colordict[k])
    colorarray = np.asarray(colorarray, dtype=np.int)

    return colorarray


def array2dict(colorarray):
    num = colorarray.shape[0]
    colordict = dict()
    for i in range(num):
        colordict[i] = list(colorarray[i])
    return colordict

In [16]:
scipy.io.savemat('CarDamage_colormap.mat', cm5)

In [17]:
import shutil
filename = 'CarDamage_colormap.mat'
src = '/content/'
destination = '/content/drive/MyDrive/Colab Notebooks/'
shutil.move(src+filename, destination+filename)

'/content/drive/MyDrive/Colab Notebooks/CarDamage_colormap.mat'

In [29]:
import PIL
import os
from PIL import Image
from tqdm.notebook import tqdm

path = '/content/instance-level_human_parsing/instance-level_human_parsing/Validation/Category_ids/'
path_list = os.listdir(path)

for i in tqdm(path_list):
  dir = path + i
  img = Image.open(dir)
  # print(img.size)
  print(np.array(img))
  print(img.size)

  0%|          | 0/5000 [00:00<?, ?it/s]

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 333)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 375)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(450, 600)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(400, 286)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 332)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 359)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 333)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  